name: Market Report Automation

on:
  schedule:
    # 5:00 AM SAST = 03:00 UTC | 5:00 PM SAST = 15:00 UTC
    - cron: '0 3,15 * * 1-5'  # Mon-Fri at 03:00 & 15:00 UTC

  # Manual trigger from GitHub UI
  workflow_dispatch:

jobs:
  generate-report:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yfinance pandas pycoingecko pillow

    - name: Generate and send report
      env:
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      run: python main.py
