name: Market Report Automation

on:
  schedule:
    - cron: '0 3,15 * * 1-5'  # 5AM & 5PM SAST (Mon-Fri)
  workflow_dispatch:

jobs:
  generate-report:
    runs-on: ubuntu-latest
    environment: marketreporternew
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Core Fonts
      run: |
        echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
        sudo apt-get update -y
        sudo apt-get install -y ttf-mscorefonts-installer
        sudo fc-cache -f -v

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install yfinance pandas pycoingecko pillow pytz

    - name: Generate Report
      env:
        MarketReport: ${{ secrets.MarketReport }}
      run: python main.py
