name: Market Report Automation

on:
  schedule:
    - cron: '0 3,15 * * 1-5'  # 5AM & 5PM SAST (Mon-Fri)
  workflow_dispatch:

jobs:
  generate-report:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libjpeg-dev zlib1g-dev ttf-mscorefonts-installer
        sudo fc-cache -f -v

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        pip install yfinance pandas pycoingecko pillow python-dotenv

    - name: Run report generator
      env:
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      run: python main.py
