name: Market Report Automation

on:
  schedule:
    - cron: '0 3,15 * * 1-5'  # 5AM & 5PM SAST (Mon-Fri)
  workflow_dispatch:

jobs:
  generate-report:
    runs-on: ubuntu-latest
    env:
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}  # Global env variable
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Validate Secrets
      run: |
        if [ -z "$EMAIL_PASSWORD" ]; then
          echo "❌ Critical Error: EMAIL_PASSWORD is not set!"
          exit 1
        else
          echo "✅ Secrets verified (password length: ${#EMAIL_PASSWORD} chars)"
        fi

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libjpeg-dev zlib1g-dev ttf-mscorefonts-installer
        sudo fc-cache -f -v

    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        pip install yfinance pandas pycoingecko pillow

    - name: Run report generator
      run: |
        echo "Current directory: $(pwd)"
        echo "Files:"
        ls -la
        python main.py

    - name: Verify outputs
      run: |
        [ -f "market_report.png" ] || (echo "❌ Infographic missing!"; exit 1)
        echo "✅ Generated files:"
        ls -lh *.png
